import { Resend } from 'resend';

import {
  BOOKING_TIMEZONE,
  MAIL_FROM,
  NOTIFICATION_EMAIL,
  getRuntimeEnv,
} from './config.js';

// Render-side helpers are kept lean and inline: no template engine, no
// per-locale dispatch table, just two functions per email kind (subject + html)
// guarded by a tiny i18n shim. The .ics attachment is generated by hand
// because all the npm libraries that produce them are huge for what we need.

type Lang = 'fr' | 'en';

interface SendInputs {
  bookingId: string;
  attendeeName: string;
  attendeeEmail: string;
  message: string | null;
  start: Date;
  end: Date;
  language: Lang;
  meetLink: string | null;
  manageUrl: string;
  cancelUrl: string;
}

let resendClient: Resend | null = null;
function getResend(): Resend {
  if (!resendClient) resendClient = new Resend(getRuntimeEnv().resendApiKey);
  return resendClient;
}

function formatHuman(date: Date, lang: Lang): string {
  return new Intl.DateTimeFormat(lang === 'fr' ? 'fr-CH' : 'en-GB', {
    timeZone: BOOKING_TIMEZONE,
    weekday: 'long',
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatIcsDate(date: Date): string {
  // YYYYMMDDTHHmmssZ — RFC 5545 UTC form.
  return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
}

function escapeIcs(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;')
    .replace(/\r\n|\r|\n/g, '\\n');
}

function quoteIcsParam(value: string): string {
  // RFC 5545 param values are DQUOTE-wrapped and must not contain DQUOTE or any
  // control character (C0 range + DEL).
  const stripped = Array.from(value)
    .filter((char) => {
      const code = char.codePointAt(0) ?? 0;
      return code >= 0x20 && code !== 0x7f && char !== String.fromCharCode(0x22);
    })
    .join("");
  return `"${stripped}"`;
}

function buildIcs(input: SendInputs): string {
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//MediaSmart//Booking//EN',
    'METHOD:REQUEST',
    'BEGIN:VEVENT',
    `UID:${input.bookingId}@mediasmart.ch`,
    `DTSTAMP:${formatIcsDate(new Date())}`,
    `DTSTART:${formatIcsDate(input.start)}`,
    `DTEND:${formatIcsDate(input.end)}`,
    'SUMMARY:' + escapeIcs(
      input.language === 'fr'
        ? 'Rendez-vous MediaSmart'
        : 'MediaSmart meeting',
    ),
    'DESCRIPTION:' + escapeIcs(
      [
        input.message ?? '',
        input.meetLink ? `Meet: ${input.meetLink}` : '',
        `Manage: ${input.manageUrl}`,
      ]
        .filter(Boolean)
        .join('\\n'),
    ),
    input.meetLink ? `LOCATION:${escapeIcs(input.meetLink)}` : 'LOCATION:Online',
    `ORGANIZER;CN=MediaSmart:mailto:${NOTIFICATION_EMAIL}`,
    `ATTENDEE;CN=${quoteIcsParam(input.attendeeName)};RSVP=TRUE:mailto:${input.attendeeEmail}`,
    'END:VEVENT',
    'END:VCALENDAR',
  ];
  return lines.join('\r\n');
}

const subjects: Record<Lang, (date: string) => { attendee: string; owner: string }> = {
  fr: (date) => ({
    attendee: `MediaSmart — confirmation pour le ${date}`,
    owner: `Nouveau rendez-vous — ${date}`,
  }),
  en: (date) => ({
    attendee: `MediaSmart — confirmed for ${date}`,
    owner: `New booking — ${date}`,
  }),
};

function buildAttendeeHtml(input: SendInputs): string {
  const when = formatHuman(input.start, input.language);
  const lang = input.language;
  const greeting = lang === 'fr' ? 'Bonjour' : 'Hi';
  const intro = lang === 'fr'
    ? `Votre rendez-vous est confirmé pour le <strong>${escapeHtml(when)}</strong> (heure suisse).`
    : `Your meeting is confirmed for <strong>${escapeHtml(when)}</strong> (Swiss time).`;
  const meetLine = input.meetLink
    ? lang === 'fr'
      ? `Lien Google Meet : <a href="${input.meetLink}">${input.meetLink}</a>`
      : `Google Meet link: <a href="${input.meetLink}">${input.meetLink}</a>`
    : '';
  const manageLine = lang === 'fr'
    ? `Pour modifier ou annuler, <a href="${input.manageUrl}">cliquez ici</a>.`
    : `To reschedule or cancel, <a href="${input.manageUrl}">click here</a>.`;
  const signoff = lang === 'fr' ? 'À très vite,' : 'Talk soon,';

  return `<!doctype html><html><body style="font-family:Inter,Helvetica,Arial,sans-serif;line-height:1.55;color:#14172D;max-width:560px;margin:0 auto;padding:24px;">
    <p style="font-size:16px;">${greeting} ${escapeHtml(input.attendeeName.split(' ')[0])},</p>
    <p style="font-size:15px;">${intro}</p>
    ${meetLine ? `<p style="font-size:15px;">${meetLine}</p>` : ''}
    <p style="font-size:15px;">${manageLine}</p>
    <p style="font-size:15px;margin-top:32px;">${signoff}<br/>MediaSmart</p>
  </body></html>`;
}

function buildOwnerHtml(input: SendInputs): string {
  const when = formatHuman(input.start, 'en');
  const safeName = escapeHtml(input.attendeeName);
  const safeEmail = escapeHtml(input.attendeeEmail);
  const safeMessage = input.message ? escapeHtml(input.message) : '<em>(no message)</em>';

  return `<!doctype html><html><body style="font-family:Inter,Helvetica,Arial,sans-serif;line-height:1.55;color:#14172D;max-width:560px;margin:0 auto;padding:24px;">
    <h2 style="font-size:18px;margin:0 0 16px;">New booking</h2>
    <p style="font-size:15px;margin:4px 0;"><strong>When:</strong> ${escapeHtml(when)} (Europe/Zurich)</p>
    <p style="font-size:15px;margin:4px 0;"><strong>Who:</strong> ${safeName} &lt;${safeEmail}&gt;</p>
    ${input.meetLink ? `<p style="font-size:15px;margin:4px 0;"><strong>Meet:</strong> <a href="${input.meetLink}">${input.meetLink}</a></p>` : ''}
    <p style="font-size:15px;margin:16px 0 4px;"><strong>Message:</strong></p>
    <p style="font-size:15px;margin:0;white-space:pre-wrap;">${safeMessage}</p>
  </body></html>`;
}

export async function sendBookingConfirmation(input: SendInputs): Promise<void> {
  const when = formatHuman(input.start, input.language);
  const { attendee, owner } = subjects[input.language](when);
  const ics = buildIcs(input);
  const icsAttachment = {
    filename: 'meeting.ics',
    content: Buffer.from(ics).toString('base64'),
    contentType: 'text/calendar; charset=utf-8; method=REQUEST',
  };

  const resend = getResend();
  await Promise.all([
    resend.emails.send({
      from: MAIL_FROM,
      to: [input.attendeeEmail],
      subject: attendee,
      html: buildAttendeeHtml(input),
      attachments: [icsAttachment],
      replyTo: NOTIFICATION_EMAIL,
    }),
    resend.emails.send({
      from: MAIL_FROM,
      to: [NOTIFICATION_EMAIL],
      subject: owner,
      html: buildOwnerHtml(input),
      replyTo: input.attendeeEmail,
    }),
  ]);
}

interface CancellationInputs {
  attendeeName: string;
  attendeeEmail: string;
  start: Date;
  language: Lang;
  rebookUrl: string;
  reason: string | null;
}

export async function sendBookingCancellation(input: CancellationInputs): Promise<void> {
  const when = formatHuman(input.start, input.language);
  const lang = input.language;
  const attendeeSubject = lang === 'fr'
    ? `MediaSmart — rendez-vous annulé (${when})`
    : `MediaSmart — meeting cancelled (${when})`;
  const ownerSubject = `Booking cancelled — ${when}`;

  const greeting = lang === 'fr' ? 'Bonjour' : 'Hi';
  const intro = lang === 'fr'
    ? `Votre rendez-vous du <strong>${escapeHtml(when)}</strong> a bien été annulé.`
    : `Your meeting on <strong>${escapeHtml(when)}</strong> has been cancelled.`;
  const rebook = lang === 'fr'
    ? `Pour reprendre rendez-vous, <a href="${input.rebookUrl}">cliquez ici</a>.`
    : `To book another time, <a href="${input.rebookUrl}">click here</a>.`;

  const attendeeHtml = `<!doctype html><html><body style="font-family:Inter,Helvetica,Arial,sans-serif;line-height:1.55;color:#14172D;max-width:560px;margin:0 auto;padding:24px;">
    <p style="font-size:16px;">${greeting} ${escapeHtml(input.attendeeName.split(' ')[0])},</p>
    <p style="font-size:15px;">${intro}</p>
    <p style="font-size:15px;">${rebook}</p>
    <p style="font-size:15px;margin-top:32px;">MediaSmart</p>
  </body></html>`;

  const ownerHtml = `<!doctype html><html><body style="font-family:Inter,Helvetica,Arial,sans-serif;line-height:1.55;color:#14172D;max-width:560px;margin:0 auto;padding:24px;">
    <h2 style="font-size:18px;margin:0 0 16px;">Booking cancelled</h2>
    <p style="font-size:15px;margin:4px 0;"><strong>When:</strong> ${escapeHtml(when)} (Europe/Zurich)</p>
    <p style="font-size:15px;margin:4px 0;"><strong>Who:</strong> ${escapeHtml(input.attendeeName)} &lt;${escapeHtml(input.attendeeEmail)}&gt;</p>
    ${input.reason ? `<p style="font-size:15px;margin:16px 0 4px;"><strong>Reason:</strong></p><p style="font-size:15px;margin:0;white-space:pre-wrap;">${escapeHtml(input.reason)}</p>` : ''}
  </body></html>`;

  const resend = getResend();
  await Promise.all([
    resend.emails.send({
      from: MAIL_FROM,
      to: [input.attendeeEmail],
      subject: attendeeSubject,
      html: attendeeHtml,
      replyTo: NOTIFICATION_EMAIL,
    }),
    resend.emails.send({
      from: MAIL_FROM,
      to: [NOTIFICATION_EMAIL],
      subject: ownerSubject,
      html: ownerHtml,
      replyTo: input.attendeeEmail,
    }),
  ]);
}
