export const cookies = {
    en: {
        title: "Cookie Management",
        subtitle: "Your privacy matters to us",
        description:
            "We use necessary cookies for the proper functioning of the site (forms, appointments, security). With your consent, we also use cookies to improve functionality, analyze performance and personalize your experience.",
        necessary: "Necessary",
        functionality: "Functionality",
        performance: "Performance",
        advertising: "Advertising",
        alwaysActive: "Always active",
        yourChoice: "Your choice",
        acceptAll: "Accept all",
        refuse: "Refuse all",
        customize: "Customize",
        detailedPrefs: "Detailed preferences",
        confirmChoices: "Confirm my choices",
        back: "Back",
        manageCookies: "Manage cookies",
        cookiesNecessary: "Necessary cookies",
        cookiesFunctionality: "Functionality cookies",
        cookiesPerformance: "Performance cookies",
        cookiesAdvertising: "Advertising cookies",
        necessaryDesc:
            "These cookies are essential for the site to function (forms, security, navigation).",
        functionalityDesc:
            "These cookies allow us to improve and personalize the website features.",
        performanceDesc:
            "These cookies allow us to measure and improve the performance of our website.",
        advertisingDesc:
            "These cookies may be used to build a profile of your interests and show you relevant advertising.",
        contactForm: "Contact form",
        contactFormDesc: "Enables message sending",
        antiSpamDesc: "Anti-spam protection",
        calendlyBasic: "Calendly (basic)",
        appointmentBooking: "Appointment booking",
        calendlyFunctionality: "Calendly - Functionality",
        calendlyFunctionalityDesc: "Improves and personalizes the booking interface",
        calendlyPerformance: "Calendly - Performance",
        calendlyPerformanceDesc: "Measures visits and improves performance",
        pagesVisited: "Pages visited, time spent, traffic source",
        calendlyTargeted: "Calendly - Targeted advertising",
        calendlyTargetedDesc: "Interest profile for relevant ads",
        themePreference: "Theme preferences",
        themePreferenceDesc: "Remembers your choice between dark and light theme",
        languagePreference: "Language preferences",
        languagePreferenceDesc: "Remembers your preferred language (FR/EN)",
        privacyLinkText: "View our privacy policy",
        ariaManageCookies: "Manage my cookies",
        ariaCloseModal: "Close the cookie window",
        ariaToggleTheme: "Toggle theme",
        ariaToggleLanguage: "Switch language",
    },
    fr: {
        title: "Gestion des cookies",
        subtitle: "Votre confidentialité compte pour nous",
        description:
            "Nous utilisons des cookies nécessaires au bon fonctionnement du site (formulaire, prise de rendez-vous, sécurité). Avec votre accord, nous utilisons également des cookies pour améliorer les fonctionnalités, analyser les performances et personnaliser votre expérience.",
        necessary: "Nécessaires",
        functionality: "Fonctionnalité",
        performance: "Performance",
        advertising: "Publicité",
        alwaysActive: "Toujours activés",
        yourChoice: "Votre choix",
        acceptAll: "Accepter tout",
        refuse: "Refuser tout",
        customize: "Personnaliser",
        detailedPrefs: "Préférences détaillées",
        confirmChoices: "Confirmer mes choix",
        back: "Retour",
        manageCookies: "Gérer les cookies",
        cookiesNecessary: "Cookies nécessaires",
        cookiesFunctionality: "Cookies de fonctionnalité",
        cookiesPerformance: "Cookies de performance",
        cookiesAdvertising: "Cookies publicitaires",
        necessaryDesc:
            "Ces cookies sont indispensables au fonctionnement du site (formulaires, sécurité, navigation).",
        functionalityDesc:
            "Ces cookies permettent d'améliorer et de personnaliser les fonctionnalités du site Web.",
        performanceDesc:
            "Ces cookies nous permettent de mesurer et d'améliorer les performances de notre site Web.",
        advertisingDesc:
            "Ces cookies peuvent être utilisés pour établir un profil de vos intérêts et vous proposer des publicités pertinentes.",
        contactForm: "Formulaire de contact",
        contactFormDesc: "Permet l'envoi de messages",
        antiSpamDesc: "Protection anti-spam",
        calendlyBasic: "Calendly (base)",
        appointmentBooking: "Réservation de rendez-vous",
        calendlyFunctionality: "Calendly - Fonctionnalité",
        calendlyFunctionalityDesc: "Améliore et personnalise l'interface de réservation",
        calendlyPerformance: "Calendly - Performance",
        calendlyPerformanceDesc: "Mesure les visites et améliore les performances",
        pagesVisited: "Pages visitées, temps passé, source de visite",
        calendlyTargeted: "Calendly - Publicité ciblée",
        calendlyTargetedDesc: "Profil d'intérêts pour publicités pertinentes",
        themePreference: "Préférences de thème",
        themePreferenceDesc: "Mémorise votre choix entre thème sombre et clair",
        languagePreference: "Préférences de langue",
        languagePreferenceDesc: "Mémorise votre langue préférée (FR/EN)",
        privacyLinkText: "Consulter notre politique de confidentialité",
        ariaManageCookies: "Gérer mes cookies",
        ariaCloseModal: "Fermer la fenêtre des cookies",
        ariaToggleTheme: "Changer de thème",
        ariaToggleLanguage: "Changer de langue",
    }
}