export const error404 = {
    en: {
        title: "Page Not Found",
        description: "This page seems to have taken a vacation in the digital space. No worries, let's explore our innovative solutions together!",
        homeButton: "Back to Home",
        homeDescription: "Discover where two worlds meet",
        backButton: "Previous Page",
        backDescription: "Go back where you came from",
        servicesTitle: "Explore Our Services",
        itServicesTitle: "IT Solutions",
        itServicesDescription: "Custom technical expertise",
        videoServicesTitle: "Video Services",
        videoServicesDescription: "Professional video production",
        contactTitle: "Need Personalized Help?",
        contactDescription: "Our team is here to turn your ideas into concrete solutions. Let's discuss your project!",
        bookingButton: "Book an Appointment",
        emailButton: "Contact Us",
        quote: "Every detour leads us to new opportunities for innovation.",
        quoteAuthor: "— The MediaSmart Team"
    },
    fr: {
        title: "Page introuvable",
        description: "Cette page semble avoir pris des vacances dans l'espace numérique. Pas de souci, explorons ensemble nos solutions innovantes !",
        homeButton: "Retour à l'accueil",
        homeDescription: "Découvrez où deux mondes se rencontrent",
        backButton: "Page précédente",
        backDescription: "Retournez d'où vous venez",
        servicesTitle: "Explorez nos services",
        itServicesTitle: "Solutions informatiques",
        itServicesDescription: "Expertise technique sur mesure",
        videoServicesTitle: "Services vidéo",
        videoServicesDescription: "Production vidéo professionnelle",
        contactTitle: "Besoin d'aide personnalisée ?",
        contactDescription: "Notre équipe est là pour transformer vos idées en solutions concrètes. Discutons de votre projet !",
        bookingButton: "Prendre rendez-vous",
        emailButton: "Nous écrire",
        quote: "Chaque détour nous mène vers de nouvelles opportunités d'innovation.",
        quoteAuthor: "— L'équipe MediaSmart"
    }
}